"""Type stubs for the gg_sdk C extension module."""

from typing import Any, Callable, Optional, Union

import enum

GgObject = Union[
    None, bool, int, float, bytes, list["GgObject"], dict[str, "GgObject"]
]

class ComponentState(enum.IntEnum):
    RUNNING = 0
    ERRORED = 1

class GgError(Exception): ...

class RetryError(GgError): ...
class BusyError(GgError): ...
class FatalError(GgError): ...
class InvalidError(GgError): ...
class UnsupportedError(GgError): ...
class ParseError(GgError): ...
class RangeError(GgError): ...
class NomemError(GgError): ...
class NoconnError(GgError): ...
class NodataError(GgError): ...
class NoentryError(GgError): ...
class ConfigError(GgError): ...
class RemoteError(GgError): ...
class TimeoutError(GgError): ...
class UnauthorizedError(GgError): ...
class ConflictError(GgError): ...

class Subscription:
    def close(self) -> None: ...
    def __enter__(self) -> "Subscription": ...
    def __exit__(self, *args: Any) -> None: ...

class Sdk:
    def __init__(self) -> None: ...
    def connect(self) -> None: ...
    def connect_with_token(self, socket_path: str, auth_token: str) -> None: ...
    def publish_to_topic(
        self, topic: str, payload: Union[dict[str, GgObject], bytes, str],
    ) -> None: ...
    def subscribe_to_topic(
        self, topic: str,
        callback: Callable[[str, Union[dict[str, GgObject], bytes]], None],
    ) -> Subscription: ...
    def publish_to_iot_core(self, topic: str, payload: bytes, qos: int) -> None: ...
    def subscribe_to_iot_core(
        self, topic: str, qos: int, callback: Callable[[str, bytes], None],
    ) -> Subscription: ...
    def update_state(self, state: ComponentState) -> None: ...
    def restart_component(self, component_name: str) -> None: ...
    def get_config(
        self, key_path: list[str], component_name: Optional[str] = None,
    ) -> GgObject: ...
    def update_config(
        self,
        key_path: list[str],
        value: GgObject,
        timestamp: Optional[float] = None,
    ) -> None: ...
    def subscribe_to_configuration_update(
        self,
        key_path: list[str],
        callback: Callable[[str, list[str]], None],
        component_name: Optional[str] = None,
    ) -> Subscription: ...
    def get_thing_shadow(
        self, thing_name: str, shadow_name: Optional[str] = None,
    ) -> bytes: ...
    def update_thing_shadow(
        self,
        thing_name: str,
        payload: bytes,
        shadow_name: Optional[str] = None,
    ) -> Optional[bytes]: ...
    def delete_thing_shadow(
        self, thing_name: str, shadow_name: Optional[str] = None,
    ) -> None: ...
    def list_named_shadows(self, thing_name: str) -> list[str]: ...
